[phases.setup]
nixPkgs = ["tesseract", "tesseract-data-jpn"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app"
